/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014 at 1:48:29 AM Eastern European Standard Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBUIPasscodeEntryFieldDelegate <NSObject>
@optional
-(void)passcodeEntryFieldDidAcceptEntry:(id)arg1;
-(void)passcodeEntryFieldDidCancelEntry:(id)arg1;
-(BOOL)passcodeEntryField:(id)arg1 shouldInsertText:(id)arg2;
-(void)passcodeEntryFieldTextDidChange:(id)arg1;

@end

