/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014 at 1:48:29 AM Eastern European Standard Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBUIPasscodeLockNumberPadDelegate <NSObject>
@optional
-(void)passcodeLockNumberPad:(id)arg1 keyDown:(id)arg2;
-(void)passcodeLockNumberPad:(id)arg1 keyUp:(id)arg2;
-(void)passcodeLockNumberPad:(id)arg1 keyCancelled:(id)arg2;
-(void)passcodeLockNumberPadCancelButtonHit:(id)arg1;
-(void)passcodeLockNumberPadBackspaceButtonHit:(id)arg1;
-(void)passcodeLockNumberPadEmergencyCallButtonHit:(id)arg1;

@end

