include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AsphaleiaPhotosProtection
AsphaleiaPhotosProtection_FILES = Tweak.xm
AsphaleiaPhotosProtection_FRAMEWORKS = UIKit
AsphaleiaPhotosProtection_CFLAGS = -fobjc-arc
AsphaleiaPhotosProtection_LDFLAGS = -L"../.theos/obj/debug"
AsphaleiaPhotosProtection_LIBRARIES = asphaleiaui

include $(THEOS_MAKE_PATH)/tweak.mk
