include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AsphaleiaFlipswitchProtection
AsphaleiaFlipswitchProtection_FILES = Tweak.xm
AsphaleiaFlipswitchProtection_CFLAGS = -fobjc-arc
AsphaleiaFlipswitchProtection_LDFLAGS = -L"../.theos/obj/debug"
AsphaleiaFlipswitchProtection_LIBRARIES = asphaleiaui

include $(THEOS_MAKE_PATH)/tweak.mk


